### ISSUE TITLE
Possible issue - used to work, now won't

### ISSUE THREAD

**Issue by bossanova808** [xbmc/kodi-addon-submitter#29]
I have used this addon submitter many times in the past and it worked well.

I noticed the change to v1.3 and updated my github action accrodingly, but every submission is failing:

```
Run xbmc/action-kodi-addon-submitter@v1.3
/usr/bin/docker run --name ca3b44b00c8204c9b84e4b459d4222e54_6458f1 --label 49859c --workdir /github/workspace --rm -e "GH_USERNAME" -e "GH_TOKEN" -e "EMAIL" -e "INPUT_KODI-REPOSITORY" -e "INPUT_KODI-VERSION" -e "INPUT_ADDON-ID" -e "INPUT_KODI-MATRIX" -e "INPUT_SUB-DIRECTORY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/weather.ozweather/weather.ozweather":"/github/workspace" 49859c:a3b44b00c8204c9b84e4b459d4222e54 "repo-scripts" "matrix" "weather.ozweather" "false" "false"
addon-submitter - INFO: Getting addon.xml file content
addon-submitter - INFO: Creating ZIP file...
addon-submitter - INFO: ZIP created successfully.
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [https://github.blog/changelog/2022-10-11...-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: [https://github.blog/changelog/2022-10-11...-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
addon-submitter - INFO: Getting addon.xml file content
urllib3.connectionpool - DEBUG: Starting new HTTPS connection (1): api.github.com:443
urllib3.connectionpool - DEBUG: [https://api.github.com:443](https://api.github.com/) "GET /repos/bossanova808/repo-scripts?type=all HTTP/1.1" 401 80
addon-submitter - INFO: Creating a personal fork of repo-scripts...
urllib3.connectionpool - DEBUG: Starting new HTTPS connection (1): api.github.com:443
urllib3.connectionpool - DEBUG: [https://api.github.com:443](https://api.github.com/) "POST /repos/xbmc/repo-scripts/forks HTTP/1.1" 401 80
Traceback (most recent call last):
File "/usr/local/bin/submit-addon", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.7/site-packages/addon_submitter/__main__.py", line 77, in main
utils.create_personal_fork(args.repo, gh_username, gh_token)
File "/usr/local/lib/python3.7/site-packages/addon_submitter/utils.py", line 202, in create_personal_fork
'GitHub API error: {}\n{}'.format(resp.status_code, resp.text)
addon_submitter.utils.AddonSubmissionError: GitHub API error: 401
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

Obviously I can see the bad credentials error at the end - but what credentials are bad, where?  I haven't changed mine, and I do have secrets for EMAIL and GH_TOKEN setup.

I alcos created a forum thread here but no-one has responded:
https://forum.kodi.tv/showthread.php?tid=371996

Sorry to push/pester but I am keen to get my submissions working again.

Help would be very much appreciated!

**Comment by bossanova808** [comment]
Apparently I needed to re-generate my github token due to github changes.  Working again, so closing this.
